//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portality.Plugins.Editor.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portality.Plugins.Editor.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    // On document load, create the editor window 
        ///    // and add it to the body
        ///    $(&quot;&lt;div /&gt;&quot;)
        ///        .attr(&quot;id&quot;, &quot;EditWindow&quot;)
        ///        .attr(&quot;title&quot;, &quot;Portality™&quot;)
        ///        .appendTo($(&quot;body&quot;))
        ///        .append(&quot;&lt;textarea id=&apos;PortalityContentBox&apos; /&gt;&quot;)
        ///        .dialog({
        ///            autoOpen: false,
        ///            minHeight: 350,
        ///            minWidth: 500,
        ///            width: 500,
        ///            height: 350,
        ///            modal: true,
        ///            buttons: {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PortalityEditorScripts {
            get {
                return ResourceManager.GetString("PortalityEditorScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 
        ///	----------------------
        ///	Portality™ | Styling
        ///	http://portality.nl
        ///	----------------------
        ///*/
        ///
        ///.normal	 {color: black}
        ///.editing {color: red}
        ///
        ///#EditWindow {
        ///	/* optional styling information */
        ///	/*font-size: 12px;*/
        ///}
        ///
        ///.editable {
        ///	/*border: 1px solid #ccc;*/
        ///}
        ///.editable:hover {
        ///	cursor: pointer;
        ///	-moz-box-shadow: 0 0 5px rgba(0,0,0,0.5);
        ///	-webkit-box-shadow: 0 0 5px rgba(0,0,0,0.5);
        ///	box-shadow: 0 0 5px rgba(0,0,0,0.5);
        ///}
        ///
        ///
        ////*
        /// * Dialog Styling
        /// */
        /// 
        ////*
        ///ui-dialog-titlebar u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PortalityEditorStyles {
            get {
                return ResourceManager.GetString("PortalityEditorStyles", resourceCulture);
            }
        }
    }
}
